name: marvelindo_outlet

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: any
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  google_nav_bar: ^5.0.6
  flutter_svg: ^1.1.6
  google_fonts: 6.1.0
  device_preview: any
  another_stepper: ^1.2.2
  mockito: ^5.4.4
  readmore: ^3.0.0
  file_picker: ^8.0.3
  path: ^1.9.0
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  # build_runner: ^2.4.9
  # freezed: ^2.5.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mv-logo.png"
  adaptive_icon_foreground: "assets/icons/mv-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/icons/
    - assets/dummy_json/
# flutter pub run build_runner build --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
