name: marvelindo_outlet

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: any
  firebase_core: any
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: any
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_convert: ^1.1.0
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mv-logo.png"
  adaptive_icon_foreground: "assets/icons/mv-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/icons/
    - assets/json_models/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
# flutter pub run build_runner build --delete-conflicting-outputs
# dart run build_runner build --delete-conflicting-outputs
