name: marvelindo_outlet

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_facebook_auth: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.0.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mv-logo.png"
  adaptive_icon_foreground: "assets/icons/mv-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
# flutter pub run build_runner build --delete-conflicting-outputs
