name: marvelindo_outlet

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  change_app_package_name: any
  cupertino_icons: any
  dartz: ^0.10.1
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_animate: any
  flutter_launcher_icons: any
  flutter_screenutil: ^5.8.4
  flutter_svg: any
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  pretty_dio_logger: ^1.3.1
  rename_app: any
  shared_preferences: ^2.2.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
